// generated by gen_step4.py - do not edit
#pragma once
#include <stdint.h>

// ops used by kunjika_v3.tflite
#define KWS_NUM_OPS 5

template <typename R>
static bool kws_register_ops(R &r)
{
    if (r.AddAveragePool2D() != kTfLiteOk) return false;   // AVERAGE_POOL_2D
    if (r.AddConv2D() != kTfLiteOk) return false;   // CONV_2D
    if (r.AddDepthwiseConv2D() != kTfLiteOk) return false;   // DEPTHWISE_CONV_2D
    if (r.AddFullyConnected() != kTfLiteOk) return false;   // FULLY_CONNECTED
    if (r.AddQuantize() != kTfLiteOk) return false;   // QUANTIZE
    return true;
}
