// generated by gen_step4.py - do not edit
#pragma once
#include <stdint.h>

// model: kunjika_v3.tflite

#define KWS_MODEL_NAME     "kunjika_v3.tflite"
#define KWS_MODEL_BYTES    16808

#define KWS_SAMPLE_RATE    16000
#define KWS_FRAME_LEN      512
#define KWS_FRAME_HOP      320
#define KWS_NUM_FRAMES     49
#define KWS_NUM_MEL        40
#define KWS_FFT_SIZE       512
#define KWS_LOG_FLOOR      1e-06f
#define KWS_MEL_LO_HZ      60.0f
#define KWS_MEL_HI_HZ      7600.0f

#define KWS_IN_SCALE       0.0943979025f
#define KWS_IN_ZERO_PT     18
#define KWS_OUT_SCALE      0.0544443727f
#define KWS_OUT_ZERO_PT    8
#define KWS_OUT_IS_LOGITS  1
#define KWS_POS_INDEX      1
